name: Next.tsx workflow
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Check code formatting
      run: npm run prettier:check
    - name: Lint files
      run: npm run lint
    - name: Run tests
      run: npm run test:ci
      env:
        CI: true
